blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.db import models


class Blog(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name="Заголовок",
        help_text="Введите заголовок",
    )
    slug = models.CharField(
        max_length=200,
        verbose_name="Slug",
        help_text="Введите slug"
    )
    content = models.TextField(
        verbose_name="Текст",
        help_text="Введите текст"
    )

    image = models.ImageField(
        upload_to="blog/image",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите изображение"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")

    views_count = models.IntegerField(default=0, verbose_name="Просмотры")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"

blog/forms.py
from django.forms import ModelForm, BooleanField
from blog.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image')

blog/views.py
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'image', 'is_published']
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        object_publ = Blog.objects.filter(is_published=True)
        context['object_publ'] = object_publ
        return context


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'image', 'is_published', ]

    def get_success_url(self):
        return reverse_lazy('blog:blog_view', kwargs={'pk': self.object.id})


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}


<div class="container col-4">
    <div class="card text-center">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                <h5 class="card-title text-center">Удалить? {{ object.title }}</h5>
                {% csrf_token %}
                <div class="card-body text-center">
                    <button type="submit" class="card-text btn btn-success">Да</button>
                    <a class="card-text btn btn-danger" href="{% url 'blog:blog_list' %}" role="button">Нет</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img src="{{ object.image| media_filter }}">
                    <div class="card-body">
                        <p class="card-text">Заголовок: {{ object.title }} ({{ object.slug }}).</p>
                        <p class="card-text"><small class="text-body-secondary">Описание: {{ object.content }}</small>
                        </p>
                        <p class="card-text">Дата создания: {{ object.created_at }}.</p>
                        <div class="form-check form-switch">

                            <label>
                                <input type="checkbox"> Активировать
                            </label>

                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-primary" href="{% url 'blog:blog_list' %}"
                                       role="button">Назад</a>
                                </div>
                                <small class="text-body-danger">Просмотры: {{ object.count_views }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


    {% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">ElectronicStore</h1>
        <p class="lead text-muted">Добавьте запись. Страница для добавление блоговой записи</p>

    </div>
</section>


<div class="container px-12">
    <div class="py-6 text-center">
        <h2>Добавьте блоговую запись</h2>
        <p class="lead">Заполните все поля.</p>
    </div>
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card ">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">ElectronicStore</h1>
        <h1 class="text-secondary">Блог</h1>
        <a href="{% url 'blog:blog_create' %}" class="btn btn-primary my-2"><i class="bi bi-android"></i>Добавить запись</a>

    </div>
</section>


<ul class="nav nav-pills justify-content-center">
    <li class="nav-item">

        <a class="nav-link {{ active }}" aria-current="page" href="{% url 'blog:blog_list' %}">Активные</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {{ inactive }}" href="{% url 'blog:blog_list' %}">Неактивные</a>
    </li>
</ul>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only"></span>
                    </a>
                    {% endif %}
                    {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                    <li class="page-item active">
                        <a class="page-link"><span class="sr-only">{{ p }}</span></a>
                    </li>
                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <li class="page-link"><a href="?page={{ p }}">{{ p }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only"></span>
                    </a>
                    {% endif %}
                </ul>
            </nav>


            {% for blog in object_list %}


            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img src="{{ blog.image| media_filter }}">
                    <div class="card-body">
                        <p class="fw-normal">{{ blog.title }}</p>
                        <p>{{ blog.content }}</p>

                        <p><a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk %}">Посмотреть
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                            </svg>
                        </a></p>
                        <p><a class="btn btn-success" href="{% url 'blog:blog_update' blog.pk %}">Редактировать
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-hammer" viewBox="0 0 16 16">
                                <path d="M9.972 2.508a.5.5 0 0 0-.16-.556l-.178-.129a5.009 5.009 0 0 0-2.076-.783C6.215.862 4.504 1.229 2.84 3.133H1.786a.5.5 0 0 0-.354.147L.146 4.567a.5.5 0 0 0 0 .706l2.571 2.579a.5.5 0 0 0 .708 0l1.286-1.29a.5.5 0 0 0 .146-.353V5.57l8.387 8.873A.5.5 0 0 0 14 14.5l1.5-1.5a.5.5 0 0 0 .017-.689l-9.129-8.63c.747-.456 1.772-.839 3.112-.839a.5.5 0 0 0 .472-.334z"/>
                            </svg>
                        </a></p>
                        <p><a class="btn btn-danger" href="{% url 'blog:blog_delete' blog.pk %}">Удалить
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd"
                                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        </a></p>
                    </div>
                </div>

            </div>
            {% endfor %}


            {% endblock %}